# Generated by Django 5.1.7 on 2025-05-15 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image_key',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
