# Generated by Django 5.1.3 on 2025-05-06 11:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frame_name', models.CharField(max_length=100)),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='frames', to='market.purchase')),
            ],
            options={
                'db_table': 'available_frame',
            },
        ),
        migrations.CreateModel(
            name='CardPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_key', models.CharField(max_length=150)),
                ('keywords', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='card_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'card_post',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField()),
                ('balance', models.IntegerField()),
                ('type', models.CharField(max_length=60)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='point_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'point_record',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserTutorialState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tutorial_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutorial_state', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_tutorial_state',
            },
        ),
    ]
