# Generated by Django 5.1.7 on 2025-05-12 16:56

from django.db import migrations, models

def backfill_was_shared(apps, schema_editor):
    CardPost = apps.get_model("join", "CardPost")
    SharedCard = apps.get_model("share", "SharedCard")

    shared_post_ids = SharedCard.objects.values_list("cardpost_id", flat=True)
    CardPost.objects.filter(id__in=shared_post_ids).update(was_shared=True)

class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_alter_cardpost_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='was_shared',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(backfill_was_shared)
    ]
