# Generated by Django 5.1.7 on 2025-05-13 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('join', '0004_add_was_shared_to_cardpost_and_backfill'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardpost',
            name='has_image_url_share_been_notified',
            field=models.BooleanField(default=False),
        ),
    ]
