# Generated by Django 5.1.7 on 2025-05-08 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycardstat',
            name='rank',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
