# Generated by Django 5.1.7 on 2025-05-07 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharedcard',
            name='is_finalized',
        ),
    ]
