# Generated by Django 5.1.7 on 2025-05-12 15:43

from django.db import migrations, models


def keep_only_first_sharedcard(apps, schema_editor):
    SharedCard = apps.get_model('share', 'SharedCard')

    # 카드 ID별로 묶고, 가장 최근 것 하나 남기고 나머지 삭제
    seen = set()
    to_delete = []

    for sc in SharedCard.objects.order_by('cardpost_id', '-created_at'):
        if sc.cardpost_id in seen:
            to_delete.append(sc.id)
        else:
            seen.add(sc.cardpost_id)

    if to_delete:
        SharedCard.objects.filter(id__in=to_delete).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('join', '0003_alter_cardpost_keyword'),
        ('share', '0002_remove_sharedcard_is_finalized'),
    ]

    operations = [
        migrations.RunPython(keep_only_first_sharedcard),
        migrations.AlterField(
            model_name='sharedcard',
            name='cardpost',
            field=models.OneToOneField(
                to='join.cardpost',
                on_delete=models.CASCADE,
                related_name='shared_card',
                help_text='원본 카드',
            ),
        ),
    ]
