# Generated by Django 5.1.7 on 2025-05-12 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0004_remove_invalid_sharedcards'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharedcard',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
