# Generated by Django 5.1.7 on 2025-05-13 01:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0005_sharedcard_like_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PinnedSharedCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_card', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_by', to='share.sharedcard')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pinned_cards', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'share_pinnedsharedcard',
                'unique_together': {('user', 'shared_card')},
            },
        ),
    ]
