# Generated by Django 5.1.7 on 2025-05-13 01:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0006_pinnedsharedcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='pinnedsharedcard',
            old_name='shared_card',
            new_name='sharedcard',
        ),
        migrations.AlterUniqueTogether(
            name='pinnedsharedcard',
            unique_together={('user', 'sharedcard')},
        ),
    ]
