# Generated by Django 5.1.7 on 2025-05-13 19:27

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0008_storedcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PinnedSharedCard',
            new_name='PinnedCard',
        ),
    ]
