# Generated by Django 5.1.7 on 2025-05-13 23:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('share', '0009_rename_pinnedsharedcard_pinnedcard'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMissionState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CardMission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(choices=[('STANDBY_POWER', '대기전력'), ('RECYCLING', '재활용'), ('SAVING', '물절약'), ('SEPARATION', '분리배출'), ('REUSABLE', '다회용기'), ('ECO_FRIENDLY', '친환경'), ('TUMBLER', '텀블러'), ('CAMPAIGN', '캠페인'), ('OTHER', '기타')], max_length=30)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mission_state', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='share.usermissionstate')),
            ],
        ),
    ]
